name: Data Quality Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
      # Adım 1: Reposu çek
      - name: Checkout code
        uses: actions/checkout@v2

      # Adım 2: Python kurulumu
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Adım 3: Gereksinimleri yükle
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Adım 4: Doğrulama scriptini çalıştır
      - name: Run data validation script
        run: python dq_pipeline.py
